### ISSUE TITLE
node_lv1과제의 git issue입니다 (node반 2조 안희재)

### ISSUE THREAD

**Issue by marioahn** [marioahn/nodebasic_lv1#1]
- git issue에서 코드 첨부가 많아서 상세 내용은 노션 링크로 대체하겠습니다!
- https://marioa.notion.site/git-issue-x-ed86b6b76ee74e4288ae0447844598e3

### [ Issue ]
- 1. 게시글 상세 조회 API에서 findOne을 이용하여 코드를 작성했는데, 더 깔끔한 코드를 고민 중 입니다
- 2. 에러 핸들링 코드에서, params가 제대로 입력 받지 못한 경우를 어떻게 테스트 하는지 궁금합니다
- 3. app.js파일에서 미들웨어 순서가 옳은지 궁금합니다

**Comment by diasm3** [comment]
1. 몽고디비 사이트에 가보시면 findOne doc을 보시면 아래와 같이 되어 있습니다. [링크](https://www.mongodb.com/docs/manual/reference/method/db.collection.findOne/)

```javascript
db.bios.findOne(
   { contribs: 'OOP' },
   { _id: 0, 'name.first': 0, birth: 0 }
)
``` 
```javascript
//수정된 결과
router.get("/", async (_, res) => {
  try {
    // try-catch
    const posts = await Post.find({}, { password: 0 })
      .sort({ createdAt: -1 })
      .exec()

    return res.status(200).json({ data: posts })
  } catch (err) {
    console.error(err)
  }
})
``` 
2. try catch 구문에서 아래 부분에서 (id값이 조회가 안되어서) 몽고디비에서 에러가 발생했습니다. 그 다음 catch로 빠지는데 return 되는 부분이 없기때문에 서버가 무한 로딩이 걸리는 것입니다. 
- 서버는 항상 request - response 로 이루어집니다. 즉 클라이언트에서 요청을 했는데 router에서 return 하지 않으면 서버는 계속 return을 기다리고 있는 것입니다.
- https://github.com/marioahn/nodebasic_lv1/blob/e550593d31a0ee77c2416f543f579adc93aa10f7/routes/posts.js#L60

3. app.js 에서 미들웨어 순서는 테스트 해보시면 흥미로운 결과를 얻으실 수 있습니다. 마음대로 순서를 바꾸셔서 실행보시면 딱히 에러가 발생 되는 부분이 없을 것입니다. 
- 에러는 발생하지 않지만 middleware를 router 밑으로 넣으면 middleware가 작동을 안하는 것을 확인 할 수 있습니다.
- 즉 router와 middleware의 순서는 상관 있다.

**Comment by marioahn** [comment]
답변 감사합니다. 문제 해결에 정말 큰 도움이 되었습니다! 말씀 해주신 대로, 코드를 전반적으로 다시 살펴봤고, 다듬었습니다.
1. 전체 조회 / 상세 조회 코드를 리팩토링하였습니다.
2. 말씀해 주신 대로 catch문에 return res.status(500)을 주어, 문제를 해결하였습니다.
3. log미들웨어와 router의 순서를 바꿨더니 log미들웨어가 작동하지 않는 점을 확인했고, 관련 내용을 주석으로 달아 놨습니다.
