### ISSUE TITLE
안녕하세요! 이번에 LV1페어가 된 김대욱입니다~

### ISSUE THREAD

**Issue by totobon6125** [marioahn/nodebasic_lv1#2]
우선 issue 를 어떻게 써야 하나 고민을 했는데 희재님이 적어주신 포멧을 그대로 사용하기로 했습니다.

1. 저는 기능 구현에만 목적을 두다 보니 각 상황별 메세지에 대해선 크게 신경을 쓰지 못했는데, 글을 작성시 요소가 하나라도 빠지면 "안내 메세지"를 하게 하게 한 점이 좋았습니다. 
2. 특히 조건문에서 부정 연산자(!) 와 논리연산자(||) 를 사용하여 코드를 구성한 거에 대해선 "이론으로 아는 것과 실제 적용은 다르구나"라는 점을 코드를 리뷰하면서 배웠습니다.
3. 이번 LV1에선 제가 배우는 것 밖에 없어 죄송(?) 스럽지만, LV2를 같이 하면서 좀 더 도움이 되는 issue를 적을 수 있도록 노력 하겠습니다.

### 제 눈엔 무언가 고쳤으면 하는 게 보이지 않네요ㅠㅠ

**Comment by marioahn** [comment]
좋은 의견 감사합니다! LV2도 같이 화이팅 해봐요!!
